### ISSUE TITLE
Authority

### ISSUE THREAD

**Issue by darqs1** [megalus/django-microsoft-sso#1]
Hi, 
I did a fork of your git with authority option: https://github.com/darqs1/django-microsoft-sso 
It gives everybody with custom login (when you have to login by "https://login.microsoftonline.com/your_tenant" instead of default "https://login.microsoftonline.com/common") to use this code.
Please look on it and add it to your main repository if you want.

**Comment by chrismaille** [comment]
Hi @darqs1, thanks for the input. If you open a Pull Request in your fork I can gratefully merge it into my project.

**Comment by darqs1** [comment]
I am beginer in github, but I have opened a Pull Request (I think).
