### ISSUE TITLE
User without mail address error

### ISSUE THREAD

**Issue by darqs1** [megalus/django-microsoft-sso#4]
Hi, 
If user doesn't have email address (and my test users in [mydomain].onmicrosoft.com doesn't have it) there is generated error. In short:
NoneType' object has no attribute 'split'
user_email_domain = self.user_email.split("@")[-1]

**Comment by chrismaille** [comment]
Ok, this is tricky, we will need a solution similar to our approach in django-github-sso. Just to be sure, you'd created these test users without email address without changing anything on your tenant configuration? In other words, the Tenant expects and works with users with no email address in your default configuration?

**Comment by darqs1** [comment]
Yes. I have multiple tenants (for prod, test etc.). And I have also multiple users: my "named" user with m365 mail, admin user with more privileges and also couple of test users. Only named user has all fields filled (mail, name, surname). Admin user has no mail and no name/surname. If I try to login this users first time the script has bad behavior: it is creating user without name (how it is possible?) and I'm gettin error.
Configuration of prod tenant was setuped by our admins, but test tenants are "out of the box".

[Edit]:
For sure, there is only Display name:
![image](https://github.com/megalus/django-microsoft-sso/assets/67951124/9a835ac3-f494-4a69-8e25-af44fb033eff)

and email is empty:
![image](https://github.com/megalus/django-microsoft-sso/assets/67951124/b93100e4-0290-491e-8032-97cccefec00f)
