### ISSUE TITLE
User without givenName and surname

### ISSUE THREAD

**Issue by darqs1** [megalus/django-microsoft-sso#6]
If user has not givenName and surname threre is an errors (because of None value in self.user_info["givenName"] and self.user_info["surname"]). Maybe it is worth to change this values to '' (empty) when they are None??

**Comment by chrismaille** [comment]
Hi @darqs1 please let me know if version 3.2.0 fix this.

**Comment by darqs1** [comment]
Prefect! Now it is working like a charm. Thank you!
