### ISSUE TITLE
There is no documentation available on how to integrate django-microsoft-sso with a Django custom user model.

### ISSUE THREAD

**Issue by ecruz91** [megalus/django-microsoft-sso#8]
Steps to Reproduce
Attempt to integrate django-microsoft-sso with the custom user model.
Encounter issues with the Django admin, specifically related to MicrosoftSSOUserAdmin.

Expected Behavior
The integration of django-microsoft-sso with a custom user model should work seamlessly, allowing for Microsoft SSO functionalities to be utilized with custom user attributes.

Actual Behavior
Encounter errors such as:
<class 'django_microsoft_sso.admin.MicrosoftSSOUserAdmin'>: (admin.E033) The value of 'ordering[0]' refers to 'username', which is not a field of 'users.User'.
<class 'django_microsoft_sso.admin.MicrosoftSSOUserAdmin'>: (admin.E108) The value of 'list_display[0]' refers to 'username', which is not a callable, an attribute of 'MicrosoftSSOUserAdmin', or an attribute or method on 'users.User'.
<class 'django_microsoft_sso.admin.MicrosoftSSOUserAdmin'>: (admin.E108) The value of 'list_display[2]' refers to 'first_name', which is not a callable, an attribute of 'MicrosoftSSOUserAdmin', or an attribute or method on 'users.User'.
<class 'django_microsoft_sso.admin.MicrosoftSSOUserAdmin'>: (admin.E108) The value of 'list_display[3]' refers to 'last_name', which is not a callable, an attribute of 'MicrosoftSSOUserAdmin', or an attribute or method on 'users.User'.

Additional Context
The Django project utilizes a custom user model (User).
Errors occur when attempting to register MicrosoftSSOUserAdmin with the custom user model in admin.py.
Running the Django development server (python manage.py runserver) results in an AlreadyRegistered error for User.
Same problem when running makemigrations

Environment
    Django version: [4.2.10]
    django-microsoft-sso version: [3.4.1]
    Python version: [3.12.2]
    Operating System: [Sonoma 14.5]

**Comment by chrismaille** [comment]
Hi @ecruz91, thanks for the message. I'll look into it.

**Comment by chrismaille** [comment]
Can you please post here the `admin.py` code for your Custom User Model Admin? I can't reproduce the error here.
